version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns:
          - "*"
          
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      all-frontend:
        patterns:
          - "*"
          
  - package-ecosystem: "npm"
    directory: "/worker"
    schedule:
      interval: "weekly"
    groups:
      all-worker:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/pc-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
