services:
  pc-api:
    build: !reset null
    image: ghcr.io/oligamiq/pdf2zh-web-translator/pc-api:production
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.40
    command:
      - --label-enable
      - --cleanup
      - --interval
      - "60"
    restart: unless-stopped
